/* Generated By:JavaCC: Do not edit this line. IDLParserVisitor.java Version 4.1d1 */
/* $Id$   *
 * (c) Copyright, eProsima, 2009.                                          *
 * All rights reserved.                                                    *    
 *                                                                         *
 * No duplications, whole or partial, manual or electronic, may be made    *
 * without express written permission.  Any such copies, or                *
 * revisions thereof, must display this notice unaltered.                  *
 * This code contains trade secrets of                                     *
 * eProsima (Proyectos y Sistemas de Mantenimiento S.L.)                   *
 *                                                                         *
 * modification history                                                    *
 * --------------------                                                    *
 * 1.1,29may12,RicM Added qos expresions.                                  *
 * 1.0,29sep09,RodM Created                                                *
 * =====================================================================   *
 */

package com.eprosima.ddsrpc.idl.ast;

////@SuppressWarnings("all")
public interface IDLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTmodule node, Object data);
  public Object visit(ASTinterfaceNode node, Object data);
  public Object visit(ASTinheritance node, Object data);
  public Object visit(ASTscoped_name node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTTypedef node, Object data);
  public Object visit(ASTSimpleType node, Object data);
  public Object visit(ASTConstructedType node, Object data);
  public Object visit(ASTsequence node, Object data);
  public Object visit(ASTstring node, Object data);
  public Object visit(ASTarray node, Object data);
  public Object visit(ASToperation node, Object data);
  public Object visit(ASTqos_exprs node, Object data);
  public Object visit(ASTqos_expr node, Object data);
  public Object visit(ASTqos_attr node, Object data);
  public Object visit(ASTop_attr node, Object data);
  public Object visit(ASTparams node, Object data);
  public Object visit(ASTparam node, Object data);
  public Object visit(ASTparam_attr node, Object data);
  public Object visit(ASTparam_type node, Object data);
  public Object visit(ASTID node, Object data);
}
/* JavaCC - OriginalChecksum=f05597502567f6d9878f53b20dd6ff5a (do not edit this line) */
