/*************************************************************************
 * Copyright (c) 2013 eProsima. All rights reserved.
 *
 * This generated file is licensed to you under the terms described in the
 * rpcdds_LICENSE file included in this rpcdds distribution.
 *
 *************************************************************************
 * 
 * @file LatencyProxy.cxx
 * This source file contains the definition of the proxy for all interfaces.
 *
 * This file was generated by the tool rpcddsgen.
 */

#include "LatencyProxy.h"
#include "rpcdds/transports/ProxyTransport.h"
#include "LatencyProtocol.h"



LatencyProxy::LatencyProxy(eprosima::rpc::transport::ProxyTransport &transport,
    eprosima::rpc::protocol::LatencyProtocol &protocol) : Proxy(transport, protocol)
{
    protocol.activateInterface("Latency");
}

LatencyProxy::~LatencyProxy()
{
}
 
st LatencyProxy::latency(/*in*/ const st& param)
{
    st return_ =
    dynamic_cast<eprosima::rpc::protocol::LatencyProtocol&>(getProtocol()).Latency_latency(param);
    return return_;
}

void LatencyProxy::latency_async(Latency_latencyCallbackHandler &obj, /*in*/ const st& param)
{
    dynamic_cast<eprosima::rpc::protocol::LatencyProtocol&>(getProtocol()).Latency_latency_async(obj, param);
}


