struct Datos
{
	long count;
	string message;
};

typedef sequence<long> largo;
typedef sequence<string> cadena;
typedef sequence<Datos> dattos;

interface SequenceTest
{
	largo getSLong(in largo l1, inout largo l2, out largo l3);
	cadena getString(in cadena s1, inout cadena s2, out cadena s3);
	dattos getStringBounded(in dattos sb1, inout dattos sb2, out dattos sb3);
};
