#ifndef _StructTest_PROXY_H_
#define _StructTest_PROXY_H_

/** 
 * Generated by DDSCS: Do not edit.  Version 1.0 *
 */

#include "client/DDSCSClient.h"
#include "StructTestRequestReplyUtils.h"
#include "StructTestClientRemoteServiceSupport.h"

class StructTestProxy : public DDSCSClient
{
    public:

        /// \brief The default constructor.
        StructTestProxy(int domainId = 0, unsigned int timeout = 3000,
        const char *qosLibrary = NULL, const char *qosProfile = NULL);

        /// \brief The default destructor.
        virtual ~StructTestProxy();

        unsigned int getTimeout();
        void setTimeout(unsigned int millis);
        
         
        DDSCSMessages
         duplicate(Envio & ev ,Recepcion  &duplicate_ret);
         
        DDSCSMessages
         suma(Envio & ev1, Envio & ev2 ,Recepcion  &suma_ret);
        
    private:
        ClientRemoteService *duplicate_Service;
        ClientRemoteService *suma_Service; 
        
        unsigned int m_timeout;
};

#endif // _StructTest_PROXY_H_
