/** 
 * Generated by DDSCS: Do not edit.  Version 1.0 *
 */

#include "StructTestClientRemoteServiceSupport.h"


/* Defines */
#define TName            duplicateClientRemoteService
#define TDataTypeSupport duplicateReplyTypeSupport
#define TData            duplicate
#define TDataSeq         duplicateReplySeq
#define TDataReader      duplicateReplyDataReader
#define TDataWriter      duplicateRequestDataWriter


#include "utils/GenericClientRemoteService.gen"


#undef TName
#undef TDataTypeSupport
#undef TData
#undef TDataSeq
#undef TDataReader
#undef TDataWriter


/* Defines */
#define TName            sumaClientRemoteService
#define TDataTypeSupport sumaReplyTypeSupport
#define TData            suma
#define TDataSeq         sumaReplySeq
#define TDataReader      sumaReplyDataReader
#define TDataWriter      sumaRequestDataWriter


#include "utils/GenericClientRemoteService.gen"


#undef TName
#undef TDataTypeSupport
#undef TData
#undef TDataSeq
#undef TDataReader
#undef TDataWriter

