#ifndef _MultithreadTest_SERVER_REMOTE_SERVICE_SUPPORT_H_
#define _MultithreadTest_SERVER_REMOTE_SERVICE_SUPPORT_H_

/** 
 * Generated by DDSCS: Do not edit.  Version 1.0 *
 */

#include "utils/GenericServerRemoteService.h"
#include "MultithreadTestRequestReplySupport.h"


GENERIC_SERVER_REMOTE_SERVICE(testServerRemoteService, testReplyDataWriter, testRequestDataReader);


#endif  // _MultithreadTest_SERVER_REMOTE_SERVICE_SUPPORT_H_