
#ifndef _MultithreadTest_REQUEST_REPLY_UTILS_H_
#define _MultithreadTest_REQUEST_REPLY_UTILS_H_

/** 
 * Generated by DDSCS: Do not edit.  Version 1.0 *
 */

#include "MultithreadTestRequestReplySupport.h"

#include "ndds_namespace_cpp.h"


class testRequestUtils
{
    public:

        static const char* registerType(DDS::DomainParticipant *clientParticipant);
         
        static testRequest* createTypeData(/*in*/ const Dato* dato1);
        
        static void extractTypeData(testRequest* data, /*in*/ Dato* &dato1);
};


class testReplyUtils
{
    public:

        static const char* registerType(DDS::DomainParticipant *clientParticipant);
         
        static testReply* createTypeData(/*out*/ const Dato* dato2, /*out*/ const DDS_Long test_ret);
        
        static void extractTypeData(testReply* data, /*out*/ Dato* &dato2, /*out*/ DDS_Long &test_ret);
};

 
#endif // _MultithreadTest_REQUEST_REPLY_UTILS_H_
