#include "Level2.idl"

module SameDirectoryNS
{
    struct SameDirectory
    {
        long count;
	Level2NS::Level2 level;
    };

    exception SameDirectoryEx
    {
        string msg;
    };

    interface SameDirectoryIfc
    {
        void mk(in SameDirectory sd, out Level2NS::Level2 lvl);
    };
};
