/* Generated By:JavaCC: Do not edit this line. IDLParserTreeConstants.java Version 4.1d1 */
package com.eprosima.ddscs.idl.ast;

import com.eprosima.ddscs.idl.*;

//@SuppressWarnings("all")
public interface IDLParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTMODULE = 2;
  public int JJTINTERFACENODE = 3;
  public int JJTINHERITANCE = 4;
  public int JJTSCOPED_NAME = 5;
  public int JJTTYPE = 6;
  public int JJTSIMPLETYPE = 7;
  public int JJTSTRING = 8;
  public int JJTARRAY = 9;
  public int JJTOPERATION = 10;
  public int JJTPARAMS = 11;
  public int JJTPARAM = 12;
  public int JJTPARAM_ATTR = 13;
  public int JJTPARAM_TYPE = 14;
  public int JJTID = 15;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "module",
    "interfaceNode",
    "inheritance",
    "scoped_name",
    "Type",
    "SimpleType",
    "string",
    "array",
    "operation",
    "params",
    "param",
    "param_attr",
    "param_type",
    "ID",
  };
}
/* JavaCC - OriginalChecksum=2f98b78fa5c8ee50acd24ac51e2af715 (do not edit this line) */
