#ifndef _EnumYStringTestSKELETON_H_
#define _EnumYStringTestSKELETON_H_

/** 
 * Generated by DDSCS: Do not edit.  Version 1.0 *
 */

#include "server/DDSCSServer.h"
#include "EnumYStringTestServerImpl.h"
#include "EnumYStringTestRequestReplyUtils.h"

class EnumYStringTestServer : public DDSCSServer
{
    private: 
      EnumYStringTestImpl *_impl;
    public:

        /// \brief The default constructor.
        EnumYStringTestServer(int domainId = 0, unsigned int threadCount = DDSCS_MIN_THREADS_DEFAULT,
        const char *qosLibrary = NULL, const char *qosProfile = NULL);

        /// \brief The default destructor.
        virtual ~EnumYStringTestServer();

        static void getEnum(DDSCSServer *server, void *requestData, ServerRemoteService *service);
        static void getString(DDSCSServer *server, void *requestData, ServerRemoteService *service);
        static void getStringBounded(DDSCSServer *server, void *requestData, ServerRemoteService *service);
};

#endif // _EnumYStringTestSKELETON_H_
