/*************************************************************************
 * Copyright (c) 2013 eProsima. All rights reserved.
 *
 * This generated file is licensed to you under the terms described in the
 * rpcdds_LICENSE file included in this rpcdds distribution.
 *
 *************************************************************************
 * 
 * @file LatencyServerImpl.h
 * This header file contains the declaration of the skeleton for all interfaces.
 *
 * This file was generated by the tool rpcddsgen.
 */

#ifndef _LatencySERVER_IMPL_H_
#define _LatencySERVER_IMPL_H_

#include "rpcdds/utils/Messages.h"
#include "Latency.h"

#include "LatencyExtension.h"



/*!
 * @brief This class is the skeleton of the servant and its remote procedures has to be implemented.
 * @ingroup LATENCY
 */
class LatencyServerImpl : public LatencyExt
{
    public:

        //! @brief The default constructor.
        LatencyServerImpl(){}

        //! @brief Destructor.
        virtual ~LatencyServerImpl(){}

;
};


#endif // _LatencySERVER_IMPL_H_