/*************************************************************************
 * Copyright (c) 2013 eProsima. All rights reserved.
 *
 * This generated file is licensed to you under the terms described in the
 * _LICENSE file included in this  distribution.
 *
 *************************************************************************
 * 
 * @file Calculator.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _Calculator_H_
#define _Calculator_H_

// TODO Poner en el contexto.
#include <rpcdds/exceptions/UserException.h>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(Calculator_SOURCE)
#define Calculator_DllAPI __declspec( dllexport )
#else
#define Calculator_DllAPI __declspec( dllimport )
#endif // Calculator_SOURCE
#else
#define Calculator_DllAPI
#endif
#else
#define Calculator_DllAPI
#endif // _WIN32

namespace eprosima
{
    namespace fastcdr
    {
        class Cdr;
    }
}

/*!
 * @brief This class represents the interface Calculator defined by the user in the IDL file.
 * @ingroup CALCULATOR
 */
class Calculator_DllAPI Calculator 
{
    public:

    virtual int32_t addition(/*in*/ int32_t value1, /*in*/ int32_t value2) = 0;

    virtual int32_t subtraction(/*in*/ int32_t value1, /*in*/ int32_t value2) = 0;

};

#endif // _Calculator_H_