#ifndef _EnumYStringTest_SERVER_RPC_SUPPORT_H_
#define _EnumYStringTest_SERVER_RPC_SUPPORT_H_

/** 
 * Generated by DDSCS: Do not edit.  Version 1.0 *
 */

#include "utils/GenericServerRPC.h"
#include "EnumYStringTestRequestReplySupport.h"



GENERIC_SERVER_RPC(EnumYStringTest_getEnumServerRPC, EnumYStringTest_getEnumReplyDataWriter, EnumYStringTest_getEnumRequestDataReader);


GENERIC_SERVER_RPC(EnumYStringTest_getStringServerRPC, EnumYStringTest_getStringReplyDataWriter, EnumYStringTest_getStringRequestDataReader);


GENERIC_SERVER_RPC(EnumYStringTest_getStringBoundedServerRPC, EnumYStringTest_getStringBoundedReplyDataWriter, EnumYStringTest_getStringBoundedRequestDataReader);


#endif  // _EnumYStringTest_SERVER_RPC_SUPPORT_H_