#include "SameDirectory.idl"
#include "util/Util.idl"
#include "Hide.idl"

module ZetaNS
{
    struct Zeta
    {
        long count;
    };
};

module IncludesTestNS
{
    struct IncludesTest
    {
        long count;
	Level2NS::Level2 level;
	SameDirectoryNS::SameDirectory sd;
    };

    interface IncludesTestIfc
    {
        IncludesTest set(in SameDirectoryNS::SameDirectory sd, inout Level2NS::Level2 lvl, out IncludesTest incl) raises(SameDirectoryNS::SameDirectoryEx);

	UtilNS::Util get() raises(UtilNS::UtilEx);

	void hide(in HideNS::Hide h, out HideNS::Hide ho);

        ZetaNS::Zeta zeta(in ZetaNS::Zeta z);
    };
};
