@Annotation
local interface RESOURCES_BASE_URI {
	attribute string value;
}

@RESOURCES_BASE_URI("http://example.com/resources/")
module FooInterface
{
	@Annotation
	local interface PATH {
		attribute string value;
	}

	@Annotation
	local interface METHOD {
		attribute string value;
	}

	@Annotation
	local interface BODY {
		attribute string value;
	}

	@PATH("Foo")
	interface FooResource
	{
		struct Emptyvoid
		{
			long status;
		};

		@METHOD("GET")
		void FooProcedure();

	};

};

