/*************************************************************************
 * Copyright (c) 2013 eProsima. All rights reserved.
 *
 * This generated file is licensed to you under the terms described in the
 * rpcdds_LICENSE file included in this rpcdds distribution.
 *
 *************************************************************************
 * 
 * @file CalculatorServerImplExample.cxx
 * This source file contains an example of the declaration of a servant.
 *
 * This file was generated by the tool rpcddsgen.
 */

#include "CalculatorServerImplExample.h"

int32_t CalculatorServerImplExample::addition(/*in*/ int32_t value1, /*in*/ int32_t value2)
{
    int32_t  addition_ret = value1 + value2;

    return addition_ret;
}

int32_t CalculatorServerImplExample::subtraction(/*in*/ int32_t value1, /*in*/ int32_t value2)
{
    int32_t  subtraction_ret = value1 - value2;

    return subtraction_ret;
}



