
#ifndef _StructTest_REQUEST_REPLY_UTILS_H_
#define _StructTest_REQUEST_REPLY_UTILS_H_

/** 
 * Generated by DDSCS: Do not edit.  Version 1.0 *
 */

#include "StructTestRequestReplySupport.h"

#include "ndds_namespace_cpp.h"


class duplicateRequestUtils
{
    public:

        static const char* registerType(DDS::DomainParticipant *clientParticipant);
         
        static duplicateRequest* createTypeData(/*in*/ const Envio* ev);
        
        static void extractTypeData(duplicateRequest* data, /*in*/ Envio* &ev);
};


class duplicateReplyUtils
{
    public:

        static const char* registerType(DDS::DomainParticipant *clientParticipant);
         
        static duplicateReply* createTypeData(/*out*/ const Recepcion* duplicate_ret);
        
        static void extractTypeData(duplicateReply* data, /*out*/ Recepcion* &duplicate_ret);
};


class sumaRequestUtils
{
    public:

        static const char* registerType(DDS::DomainParticipant *clientParticipant);
         
        static sumaRequest* createTypeData(/*in*/ const Envio* ev1, /*in*/ const Envio* ev2);
        
        static void extractTypeData(sumaRequest* data, /*in*/ Envio* &ev1, /*in*/ Envio* &ev2);
};


class sumaReplyUtils
{
    public:

        static const char* registerType(DDS::DomainParticipant *clientParticipant);
         
        static sumaReply* createTypeData(/*out*/ const Recepcion* suma_ret);
        
        static void extractTypeData(sumaReply* data, /*out*/ Recepcion* &suma_ret);
};

 
#endif // _StructTest_REQUEST_REPLY_UTILS_H_
