/*************************************************************************
 * Copyright (c) 2012 eProsima. All rights reserved.
 *
 * This copy of RPCDDS is licensed to you under the terms described in the
 * RPCDDS_LICENSE file included in this distribution.
 *
 *************************************************************************
 * 
 * @file StructTestClientRPCSupport.cxx
 * This source file contains the definition of the proxy's RPC endpoints for interface StructTest.
 *
 * This file was generated by the tool rpcddsgen.
 */

#include "StructTestClientRPCSupport.h"


/* Defines */
#define TName            StructTest_duplicateClientRPC
#define TDataTypeSupport StructTest_duplicateReplyTypeSupport
#define TData            StructTest_duplicate
#define TDataSeq         StructTest_duplicateReplySeq
#define TDataReader      StructTest_duplicateReplyDataReader
#define TDataWriter      StructTest_duplicateRequestDataWriter


#include "utils/GenericClientRPC.gen"


#undef TName
#undef TDataTypeSupport
#undef TData
#undef TDataSeq
#undef TDataReader
#undef TDataWriter


/* Defines */
#define TName            StructTest_sumaClientRPC
#define TDataTypeSupport StructTest_sumaReplyTypeSupport
#define TData            StructTest_suma
#define TDataSeq         StructTest_sumaReplySeq
#define TDataReader      StructTest_sumaReplyDataReader
#define TDataWriter      StructTest_sumaRequestDataWriter


#include "utils/GenericClientRPC.gen"


#undef TName
#undef TDataTypeSupport
#undef TData
#undef TDataSeq
#undef TDataReader
#undef TDataWriter

