#ifndef _StructTest_ASYNC_SUPPORT_H_
#define _StructTest_ASYNC_SUPPORT_H_

/** 
 * Generated by DDSCS: Do not edit.  Version 1.0 *
 */

#include "client/AsyncTask.h"


class StructTest_duplicateTask : public eProsima::DDSRPC::AsyncTask
{
    public:

        /// \brief The default constructor.
        StructTest_duplicateTask(StructTest_duplicateCallbackHandler &obj,
           eProsima::DDSRPC::Client *client);

        /// \brief The default destructor.
        virtual ~StructTest_duplicateTask();
        
        virtual void execute();
        
        virtual void on_exception(const eProsima::DDSRPC::SystemException &ex);
        
        StructTest_duplicateCallbackHandler& getObject();
        
        void* getReplyInstance();
        
        private:
        
           StructTest_duplicateCallbackHandler &m_obj;
           
           StructTest_duplicateReply m_reply;
};

class StructTest_sumaTask : public eProsima::DDSRPC::AsyncTask
{
    public:

        /// \brief The default constructor.
        StructTest_sumaTask(StructTest_sumaCallbackHandler &obj,
           eProsima::DDSRPC::Client *client);

        /// \brief The default destructor.
        virtual ~StructTest_sumaTask();
        
        virtual void execute();
        
        virtual void on_exception(const eProsima::DDSRPC::SystemException &ex);
        
        StructTest_sumaCallbackHandler& getObject();
        
        void* getReplyInstance();
        
        private:
        
           StructTest_sumaCallbackHandler &m_obj;
           
           StructTest_sumaReply m_reply;
};

#endif // _StructTest_ASYNC_SUPPORT_H_