#ifndef _UnionTest_CLIENT_RPC_SUPPORT_H_
#define _UnionTest_CLIENT_RPC_SUPPORT_H_

/** 
 * Generated by DDSCS: Do not edit.  Version 1.0 *
 */

#include "utils/GenericClientRPC.h"
#include "UnionTestRequestReplySupport.h"


GENERIC_CLIENT_RPC(UnionTest_getEmpleadoClientRPC, UnionTest_getEmpleadoRequestDataWriter, UnionTest_getEmpleadoReplyDataReader);


#endif  // _UnionTest_CLIENT_RPC_SUPPORT_H_