/** 
 * Generated by DDSRPC   *
 * Simplest server main  *
 */

#include "UnionTestServer.h"

int main()
{
    int returnedValue = 0;
    int domainId = 0;
    unsigned int threadPoolSize = 5;
    UnionTestServer *server = new UnionTestServer(domainId, threadPoolSize);
    server->executeServer();

    delete server;
}
