#ifndef _UnionTest_ASYNC_SUPPORT_H_
#define _UnionTest_ASYNC_SUPPORT_H_

/** 
 * Generated by DDSCS: Do not edit.  Version 1.0 *
 */

#include "client/AsyncTask.h"


class UnionTest_getEmpleadoTask : public eProsima::DDSRPC::AsyncTask
{
    public:

        /// \brief The default constructor.
        UnionTest_getEmpleadoTask(UnionTest_getEmpleadoCallbackHandler &obj,
           eProsima::DDSRPC::Client *client);

        /// \brief The default destructor.
        virtual ~UnionTest_getEmpleadoTask();
        
        virtual void execute();
        
        virtual void on_exception(const eProsima::DDSRPC::SystemException &ex);
        
        UnionTest_getEmpleadoCallbackHandler& getObject();
        
        void* getReplyInstance();
        
        private:
        
           UnionTest_getEmpleadoCallbackHandler &m_obj;
           
           UnionTest_getEmpleadoReply m_reply;
};

#endif // _UnionTest_ASYNC_SUPPORT_H_