#ifndef _SequenceTestSERVER_IMPL_H_
#define _SequenceTestSERVER_IMPL_H_

/** 
 * Generated by DDSCS: Do not edit.  Version 1.0 *
 */

#include "utils/Messages.h"
#include "SequenceTestRequestReplyUtils.h"

class SequenceTestServerImpl
{
    public:

        /// \brief The default constructor.
        SequenceTestServerImpl();

        /// \brief The default destructor.
        virtual ~SequenceTestServerImpl();

         
        eProsima::DDSRPC::ReturnMessage getSLong(/*in*/ const largo* l1, /*inout*/ largo* &l2, /*out*/ largo* &l3, /*out*/ largo* &getSLong_ret);
         
        eProsima::DDSRPC::ReturnMessage getString(/*in*/ const cadena* s1, /*inout*/ cadena* &s2, /*out*/ cadena* &s3, /*out*/ cadena* &getString_ret);
         
        eProsima::DDSRPC::ReturnMessage getStringBounded(/*in*/ const dattos* sb1, /*inout*/ dattos* &sb2, /*out*/ dattos* &sb3, /*out*/ dattos* &getStringBounded_ret);
};

#endif // _SequenceTestSERVER_IMPL_H_