/** 
 * Generated by DDSCS: Do not edit.  Version 1.0 *
 */

#include "EnumYStringTestRequestReplyUtils.h"
#include "EnumYStringTestRequestReplyPlugin.h"


const char* getEnumRequestUtils::registerType(DDS::DomainParticipant *clientParticipant)
{
    const char *typeName = NULL;

    if(clientParticipant != NULL)
    {
        typeName = getEnumRequestTypeSupport::get_type_name();

        if(getEnumRequestTypeSupport::register_type(clientParticipant, typeName) != DDS::RETCODE_OK)
        {
            return NULL;
        }
    }

    return typeName;
}

getEnumRequest* getEnumRequestUtils::createTypeData(/*in*/ const Valores v1, /*inout*/ const Valores v2)
{
    getEnumRequest* instance = getEnumRequestTypeSupport::create_data();

    instance->v1 = v1;
    instance->v2 = v2;
    
    
    return instance;
}

void getEnumRequestUtils::extractTypeData(getEnumRequest* data , /*in*/ Valores &v1, /*inout*/ Valores &v2)
{
    v1 = data->v1;
    v2 = data->v2;
    
    
}


const char* getEnumReplyUtils::registerType(DDS::DomainParticipant *clientParticipant)
{
    const char *typeName = NULL;

    if(clientParticipant != NULL)
    {
        typeName = getEnumReplyTypeSupport::get_type_name();

        if(getEnumReplyTypeSupport::register_type(clientParticipant, typeName) != DDS::RETCODE_OK)
        {
            return NULL;
        }
    }

    return typeName;
}

getEnumReply* getEnumReplyUtils::createTypeData(/*inout*/ const Valores v2, /*out*/ const Valores v3, /*out*/ const Valores getEnum_ret)
{
    getEnumReply* instance = getEnumReplyTypeSupport::create_data();

    instance->v2 = v2;
    instance->v3 = v3;
    
    instance->getEnum_ret = getEnum_ret;            
    return instance;
}

void getEnumReplyUtils::extractTypeData(getEnumReply* data , /*inout*/ Valores &v2, /*out*/ Valores &v3, /*out*/ Valores &getEnum_ret)
{
    v2 = data->v2;
    v3 = data->v3;
    
    getEnum_ret = data->getEnum_ret;            
}


const char* getStringRequestUtils::registerType(DDS::DomainParticipant *clientParticipant)
{
    const char *typeName = NULL;

    if(clientParticipant != NULL)
    {
        typeName = getStringRequestTypeSupport::get_type_name();

        if(getStringRequestTypeSupport::register_type(clientParticipant, typeName) != DDS::RETCODE_OK)
        {
            return NULL;
        }
    }

    return typeName;
}

getStringRequest* getStringRequestUtils::createTypeData(/*in*/ const char* s1, /*inout*/ const char* s2)
{
    getStringRequest* instance = getStringRequestTypeSupport::create_data();

    if(instance->s1 != NULL)
       free(instance->s1);
    instance->s1 = strdup(s1);
    if(instance->s2 != NULL)
       free(instance->s2);
    instance->s2 = strdup(s2);
    
    
    return instance;
}

void getStringRequestUtils::extractTypeData(getStringRequest* data , /*in*/ char* &s1, /*inout*/ char* &s2)
{
    s1 = data->s1;
    s2 = strdup(data->s2);
    
    
}


const char* getStringReplyUtils::registerType(DDS::DomainParticipant *clientParticipant)
{
    const char *typeName = NULL;

    if(clientParticipant != NULL)
    {
        typeName = getStringReplyTypeSupport::get_type_name();

        if(getStringReplyTypeSupport::register_type(clientParticipant, typeName) != DDS::RETCODE_OK)
        {
            return NULL;
        }
    }

    return typeName;
}

getStringReply* getStringReplyUtils::createTypeData(/*inout*/ const char* s2, /*out*/ const char* s3, /*out*/ const char* getString_ret)
{
    getStringReply* instance = getStringReplyTypeSupport::create_data();

    if(instance->s2 != NULL)
       free(instance->s2);
    instance->s2 = strdup(s2);
    if(instance->s3 != NULL)
       free(instance->s3);
    instance->s3 = strdup(s3);
    
    if(instance->getString_ret != NULL)
       free(instance->getString_ret);
    instance->getString_ret = strdup(getString_ret);            
    return instance;
}

void getStringReplyUtils::extractTypeData(getStringReply* data , /*inout*/ char* &s2, /*out*/ char* &s3, /*out*/ char* &getString_ret)
{
    s2 = strdup(data->s2);
    s3 = strdup(data->s3);
    
    getString_ret = strdup(data->getString_ret);            
}


const char* getStringBoundedRequestUtils::registerType(DDS::DomainParticipant *clientParticipant)
{
    const char *typeName = NULL;

    if(clientParticipant != NULL)
    {
        typeName = getStringBoundedRequestTypeSupport::get_type_name();

        if(getStringBoundedRequestTypeSupport::register_type(clientParticipant, typeName) != DDS::RETCODE_OK)
        {
            return NULL;
        }
    }

    return typeName;
}

getStringBoundedRequest* getStringBoundedRequestUtils::createTypeData(/*in*/ const char* sb1, /*inout*/ const char* sb2)
{
    getStringBoundedRequest* instance = getStringBoundedRequestTypeSupport::create_data();

    if(instance->sb1 != NULL)
       free(instance->sb1);
    instance->sb1 = strdup(sb1);
    if(instance->sb2 != NULL)
       free(instance->sb2);
    instance->sb2 = strdup(sb2);
    
    
    return instance;
}

void getStringBoundedRequestUtils::extractTypeData(getStringBoundedRequest* data , /*in*/ char* &sb1, /*inout*/ char* &sb2)
{
    sb1 = data->sb1;
    sb2 = strdup(data->sb2);
    
    
}


const char* getStringBoundedReplyUtils::registerType(DDS::DomainParticipant *clientParticipant)
{
    const char *typeName = NULL;

    if(clientParticipant != NULL)
    {
        typeName = getStringBoundedReplyTypeSupport::get_type_name();

        if(getStringBoundedReplyTypeSupport::register_type(clientParticipant, typeName) != DDS::RETCODE_OK)
        {
            return NULL;
        }
    }

    return typeName;
}

getStringBoundedReply* getStringBoundedReplyUtils::createTypeData(/*inout*/ const char* sb2, /*out*/ const char* sb3, /*out*/ const char* getStringBounded_ret)
{
    getStringBoundedReply* instance = getStringBoundedReplyTypeSupport::create_data();

    if(instance->sb2 != NULL)
       free(instance->sb2);
    instance->sb2 = strdup(sb2);
    if(instance->sb3 != NULL)
       free(instance->sb3);
    instance->sb3 = strdup(sb3);
    
    if(instance->getStringBounded_ret != NULL)
       free(instance->getStringBounded_ret);
    instance->getStringBounded_ret = strdup(getStringBounded_ret);            
    return instance;
}

void getStringBoundedReplyUtils::extractTypeData(getStringBoundedReply* data , /*inout*/ char* &sb2, /*out*/ char* &sb3, /*out*/ char* &getStringBounded_ret)
{
    sb2 = strdup(data->sb2);
    sb3 = strdup(data->sb3);
    
    getStringBounded_ret = strdup(data->getStringBounded_ret);            
}

 