/** 
 * Generated by DDSCS: Do not edit.  Version 1.0 *
 */

#include "EnumYStringTestServer.h"
#include "transports/UDPTransport.h"
#include "transports/TCPTransport.h"
#include "EnumYStringTestRequestReplyPlugin.h"

#include "EnumYStringTestServerRPCSupport.h"

EnumYStringTestServer::EnumYStringTestServer(eProsima::DDSRPC::ServerStrategy *strategy,
    int domainId) :
    Server(strategy, NULL, domainId)
{
    _impl = new EnumYStringTestServerImpl();

    createRPCs();
}

EnumYStringTestServer::EnumYStringTestServer(eProsima::DDSRPC::ServerStrategy *strategy,
    eProsima::DDSRPC::Transport *transport, int domainId) :
    Server(strategy, transport, domainId)
{
    _impl = new EnumYStringTestServerImpl();
    
    createRPCs();
}

EnumYStringTestServer::~EnumYStringTestServer()
{
    delete _impl;    
}

void EnumYStringTestServer::createRPCs()
{
    this->setRPC(new getEnumServerRPC("getEnum", this,
                getEnumRequestUtils::registerType(getParticipant()),
                getEnumReplyUtils::registerType(getParticipant()),
                &EnumYStringTestServer::getEnum, getParticipant()));
    this->setRPC(new getStringServerRPC("getString", this,
                getStringRequestUtils::registerType(getParticipant()),
                getStringReplyUtils::registerType(getParticipant()),
                &EnumYStringTestServer::getString, getParticipant()));
    this->setRPC(new getStringBoundedServerRPC("getStringBounded", this,
                getStringBoundedRequestUtils::registerType(getParticipant()),
                getStringBoundedReplyUtils::registerType(getParticipant()),
                &EnumYStringTestServer::getStringBounded, getParticipant()));

}

void EnumYStringTestServer::getEnum(eProsima::DDSRPC::Server *server, void *requestData, eProsima::DDSRPC::ServerRPC *service) 
{ 
    EnumYStringTestServer *srv = dynamic_cast<EnumYStringTestServer*>(server);
    Valores  v1 = VALOR1;    
    Valores  v2 = VALOR1;    
    Valores  v3 = VALOR1;    
    Valores  returnedValue = VALOR1;       
    getEnumReply replyData;

    getEnumRequestUtils::extractTypeData(*(getEnumRequest*)requestData, v1  , v2  );

returnedValue = srv->_impl->getEnum(v1  , v2  , v3  );

    getEnumReplyUtils::setTypeData(replyData, v2  , v3  , returnedValue);

    // sendReply takes care of deleting the data
    service->sendReply(requestData, &replyData, eProsima::DDSRPC::OPERATION_SUCCESSFUL);
    
    getEnumRequestTypeSupport::delete_data((getEnumRequest*)requestData);
    
        
        
        
}
void EnumYStringTestServer::getString(eProsima::DDSRPC::Server *server, void *requestData, eProsima::DDSRPC::ServerRPC *service) 
{ 
    EnumYStringTestServer *srv = dynamic_cast<EnumYStringTestServer*>(server);
    char*  s1 = NULL;    
    char*  s2 = NULL;    
    char*  s3 = NULL;    
    char*  returnedValue = NULL;       
    getStringReply replyData;

    getStringRequestUtils::extractTypeData(*(getStringRequest*)requestData, s1  , s2  );

returnedValue = srv->_impl->getString(s1  , s2  , s3  );

    getStringReplyUtils::setTypeData(replyData, s2  , s3  , returnedValue);

    // sendReply takes care of deleting the data
    service->sendReply(requestData, &replyData, eProsima::DDSRPC::OPERATION_SUCCESSFUL);
    
    getStringRequestTypeSupport::delete_data((getStringRequest*)requestData);
    
    if(returnedValue != NULL) free(returnedValue);    
    if(s2 != NULL) free(s2);    
    if(s3 != NULL) free(s3);    
}
void EnumYStringTestServer::getStringBounded(eProsima::DDSRPC::Server *server, void *requestData, eProsima::DDSRPC::ServerRPC *service) 
{ 
    EnumYStringTestServer *srv = dynamic_cast<EnumYStringTestServer*>(server);
    char*  sb1 = NULL;    
    char*  sb2 = NULL;    
    char*  sb3 = NULL;    
    char*  returnedValue = NULL;       
    getStringBoundedReply replyData;

    getStringBoundedRequestUtils::extractTypeData(*(getStringBoundedRequest*)requestData, sb1  , sb2  );

returnedValue = srv->_impl->getStringBounded(sb1  , sb2  , sb3  );

    getStringBoundedReplyUtils::setTypeData(replyData, sb2  , sb3  , returnedValue);

    // sendReply takes care of deleting the data
    service->sendReply(requestData, &replyData, eProsima::DDSRPC::OPERATION_SUCCESSFUL);
    
    getStringBoundedRequestTypeSupport::delete_data((getStringBoundedRequest*)requestData);
    
    if(returnedValue != NULL) free(returnedValue);    
    if(sb2 != NULL) free(sb2);    
    if(sb3 != NULL) free(sb3);    
}