/** 
 * Generated by DDSCS: Do not edit.  Version 1.0 *
 */

#include "server/Server.h"
#include "OnewayCallTestServerRPCSupport.h"


/* Defines */
#define TName                   OnewayCallTest_setLongServerRPC
#define TDataReplyTypeSupport   OnewayCallTest_setLongReplyTypeSupport
#define TDataRequestTypeSupport OnewayCallTest_setLongRequestTypeSupport
#define TData                   OnewayCallTest_setLong
#define TDataReader             OnewayCallTest_setLongRequestDataReader
#define TDataWriter             OnewayCallTest_setLongReplyDataWriter
#define IS_ONEWAY


#include "utils/GenericServerRPC.gen"


#undef TName
#undef TDataReplyTypeSupport
#undef TDataRequestTypeSupport
#undef TData
#undef TDataReader
#undef TDataWriter
#undef IS_ONEWAY


/* Defines */
#define TName                   OnewayCallTest_getLongServerRPC
#define TDataReplyTypeSupport   OnewayCallTest_getLongReplyTypeSupport
#define TDataRequestTypeSupport OnewayCallTest_getLongRequestTypeSupport
#define TData                   OnewayCallTest_getLong
#define TDataReader             OnewayCallTest_getLongRequestDataReader
#define TDataWriter             OnewayCallTest_getLongReplyDataWriter


#include "utils/GenericServerRPC.gen"


#undef TName
#undef TDataReplyTypeSupport
#undef TDataRequestTypeSupport
#undef TData
#undef TDataReader
#undef TDataWriter


/* Defines */
#define TName                   OnewayCallTest_setBooleanServerRPC
#define TDataReplyTypeSupport   OnewayCallTest_setBooleanReplyTypeSupport
#define TDataRequestTypeSupport OnewayCallTest_setBooleanRequestTypeSupport
#define TData                   OnewayCallTest_setBoolean
#define TDataReader             OnewayCallTest_setBooleanRequestDataReader
#define TDataWriter             OnewayCallTest_setBooleanReplyDataWriter
#define IS_ONEWAY


#include "utils/GenericServerRPC.gen"


#undef TName
#undef TDataReplyTypeSupport
#undef TDataRequestTypeSupport
#undef TData
#undef TDataReader
#undef TDataWriter
#undef IS_ONEWAY


/* Defines */
#define TName                   OnewayCallTest_getBooleanServerRPC
#define TDataReplyTypeSupport   OnewayCallTest_getBooleanReplyTypeSupport
#define TDataRequestTypeSupport OnewayCallTest_getBooleanRequestTypeSupport
#define TData                   OnewayCallTest_getBoolean
#define TDataReader             OnewayCallTest_getBooleanRequestDataReader
#define TDataWriter             OnewayCallTest_getBooleanReplyDataWriter


#include "utils/GenericServerRPC.gen"


#undef TName
#undef TDataReplyTypeSupport
#undef TDataRequestTypeSupport
#undef TData
#undef TDataReader
#undef TDataWriter


/* Defines */
#define TName                   OnewayCallTest_setStringServerRPC
#define TDataReplyTypeSupport   OnewayCallTest_setStringReplyTypeSupport
#define TDataRequestTypeSupport OnewayCallTest_setStringRequestTypeSupport
#define TData                   OnewayCallTest_setString
#define TDataReader             OnewayCallTest_setStringRequestDataReader
#define TDataWriter             OnewayCallTest_setStringReplyDataWriter
#define IS_ONEWAY


#include "utils/GenericServerRPC.gen"


#undef TName
#undef TDataReplyTypeSupport
#undef TDataRequestTypeSupport
#undef TData
#undef TDataReader
#undef TDataWriter
#undef IS_ONEWAY


/* Defines */
#define TName                   OnewayCallTest_getStringServerRPC
#define TDataReplyTypeSupport   OnewayCallTest_getStringReplyTypeSupport
#define TDataRequestTypeSupport OnewayCallTest_getStringRequestTypeSupport
#define TData                   OnewayCallTest_getString
#define TDataReader             OnewayCallTest_getStringRequestDataReader
#define TDataWriter             OnewayCallTest_getStringReplyDataWriter


#include "utils/GenericServerRPC.gen"


#undef TName
#undef TDataReplyTypeSupport
#undef TDataRequestTypeSupport
#undef TData
#undef TDataReader
#undef TDataWriter


/* Defines */
#define TName                   OnewayCallTest_setStructServerRPC
#define TDataReplyTypeSupport   OnewayCallTest_setStructReplyTypeSupport
#define TDataRequestTypeSupport OnewayCallTest_setStructRequestTypeSupport
#define TData                   OnewayCallTest_setStruct
#define TDataReader             OnewayCallTest_setStructRequestDataReader
#define TDataWriter             OnewayCallTest_setStructReplyDataWriter
#define IS_ONEWAY


#include "utils/GenericServerRPC.gen"


#undef TName
#undef TDataReplyTypeSupport
#undef TDataRequestTypeSupport
#undef TData
#undef TDataReader
#undef TDataWriter
#undef IS_ONEWAY


/* Defines */
#define TName                   OnewayCallTest_getStructServerRPC
#define TDataReplyTypeSupport   OnewayCallTest_getStructReplyTypeSupport
#define TDataRequestTypeSupport OnewayCallTest_getStructRequestTypeSupport
#define TData                   OnewayCallTest_getStruct
#define TDataReader             OnewayCallTest_getStructRequestDataReader
#define TDataWriter             OnewayCallTest_getStructReplyDataWriter


#include "utils/GenericServerRPC.gen"


#undef TName
#undef TDataReplyTypeSupport
#undef TDataRequestTypeSupport
#undef TData
#undef TDataReader
#undef TDataWriter

