struct Estructura
{
    long valor1;
    long valor2;
    string valor3;
    sequence<long, 500> seq;
};

interface SimpleDelay
{
    long suma(in long value1, in long value2);
    Estructura duplicate(in Estructura es);
};

