/*************************************************************************
 * Copyright (c) 2013 eProsima. All rights reserved.
 *
 * This generated file is licensed to you under the terms described in the
 * fastrpc_LICENSE file included in this fastrpc distribution.
 *
 *************************************************************************
 * 
 * @file InheritanceServerImplExample.cxx
 * This source file contains an example of the declaration of a servant.
 *
 * This file was generated by the tool fastrpcgen.
 */

#include "InheritanceServerImplExample.h"
#include <fastrpc/utils/Utilities.h>

static ModuleA::Interface1::Dato function1_data;
static bool function1_set_call = false;
static ModuleA::Interface1::Dato function1_data2;
static bool function1_set_call2 = false;
static ModuleA::Interface1::Dato function1_data3;
static bool function1_set_call3 = false;

ModuleA::Interface1::Dato Interface1ServerImplExample::function1(/*in*/ const ModuleA::Interface1::Dato& data)
{
    ModuleA::Interface1::Dato  return_;

    return_.count = data.count + 1;
   
    return return_;
} 

void Interface1ServerImplExample::function1_set(/*in*/ const ModuleA::Interface1::Dato& data)
{
    function1_data = data;
    function1_data.count = data.count + 1;
    function1_set_call = true;
} 

ModuleA::Interface1::Dato Interface1ServerImplExample::function1_get()
{
    while(!function1_set_call)
        eprosima::rpc::sleep(100);
    return function1_data;
} 






ModuleA::Interface1::Dato Interface2ServerImplExample::function1(/*in*/ const ModuleA::Interface1::Dato& data)
{
    ModuleA::Interface1::Dato  return_;

    return_.count = data.count;
   
    return return_;
} 

void Interface2ServerImplExample::function1_set(/*in*/ const ModuleA::Interface1::Dato& data)
{
    function1_data2.count = data.count;
    function1_set_call2 = true;
} 

ModuleA::Interface1::Dato Interface2ServerImplExample::function1_get()
{
    while(!function1_set_call2)
        eprosima::rpc::sleep(100);
    return function1_data2;
} 

int32_t Interface2ServerImplExample::function2(/*in*/ int32_t count)
{
    return count;
} 




ModuleA::Interface1::Dato Interface3ServerImplExample::function1(/*in*/ const ModuleA::Interface1::Dato& data)
{
    ModuleA::Interface1::Dato  return_;

    return_.count = data.count + 2;
   
    return return_;
} 

void Interface3ServerImplExample::function1_set(/*in*/ const ModuleA::Interface1::Dato& data)
{
    function1_data3.count = data.count + 2;
    function1_set_call3 = true;
} 

ModuleA::Interface1::Dato Interface3ServerImplExample::function1_get()
{
    while(!function1_set_call3)
        eprosima::rpc::sleep(100);
    return function1_data3;
} 

ModuleB::Interface3::Dato Interface3ServerImplExample::function3(/*in*/ const ModuleB::Interface3::Dato& data)
{
    ModuleB::Interface3::Dato return_;

    return_.str = DDS_String_dup(data.str);

    return return_;
} 




