/** 
 * Generated by DDSRPC                                              *
 * Empty interface implementation to be filled with your own code.  *
 */

#include "ServerExceptionServerImpl.h"
#include "exceptions/ServerInternalException.h"

ServerExceptionServerImpl::ServerExceptionServerImpl()
{
}
ServerExceptionServerImpl::~ServerExceptionServerImpl()
{
}


void ServerExceptionServerImpl::sendException() 
{
    throw eProsima::DDSRPC::ServerInternalException("Testing exception");
} 

char* ServerExceptionServerImpl::sendExceptionTwo(/*in*/ char* message, /*inout*/ char*& message2, /*out*/ char*& message3) 
{
    char*  sendExceptionTwo_ret = NULL;

    throw eProsima::DDSRPC::ServerInternalException("Testing exception");

    return sendExceptionTwo_ret;
} 

Estructura ServerExceptionServerImpl::sendExceptionThree(/*in*/ const Estructura& es, /*inout*/ Estructura& es2, /*out*/ Estructura& es3) 
{
    Estructura sendExceptionThree_ret;

    throw eProsima::DDSRPC::ServerInternalException("Testing exception");

    return sendExceptionThree_ret;
} 
