/** 
 * Generated by DDSCS: Do not edit.  Version 1.0 *
 */

#include "HelloWorldAsyncClientRPCSupport.h"


/* Defines */
#define TName            sumaClientRPC
#define TDataTypeSupport sumaReplyTypeSupport
#define TData            suma
#define TDataSeq         sumaReplySeq
#define TDataReader      sumaReplyDataReader
#define TDataWriter      sumaRequestDataWriter


#include "utils/GenericClientRPC.gen"


#undef TName
#undef TDataTypeSupport
#undef TData
#undef TDataSeq
#undef TDataReader
#undef TDataWriter

