/*************************************************************************
 * Copyright (c) 2013 eProsima. All rights reserved.
 *
 * This copy of FASTRPC is licensed to you under the terms described in the
 * FASTRPC_LICENSE file included in this distribution.
 *
 *************************************************************************/

module dds
{
    typedef octet GuidPrefix_t[12];

    struct EntityId_t
    {
        octet entityKey[3];
        octet entityKind;
    };

    struct GUID_t
    {
        GuidPrefix_t guidPrefix;
        EntityId_t entityId;
    };

    struct SequenceNumber_t
    {
        long high;
        unsigned long low;
    };

    struct SampleIdentity
    {
        GUID_t writer_guid;
        SequenceNumber_t sequence_number;
    };

    module rpc
    {
        typedef octet UnknownOperation;
        typedef octet UnknownException;
        typedef octet UnusedMember;

        enum RemoteExceptionCode_t
        {
            REMOTE_EX_OK,
            REMOTE_EX_UNSUPPORTED,
            REMOTE_EX_INVALID_ARGUMENT,
            REMOTE_EX_OUT_OF_RESOURCES,
            REMOTE_EX_UNKNOWN_OPERATION,
            REMOTE_EX_UNKNOWN_EXCEPTION
        };

        /*!
         * @brief Header information used in all generated request topics.
         */
        struct RequestHeader
        {
            //! @brief Identification of the client that sends the request.
            dds::SampleIdentity requestId;
            string<255> instanceName;
        }; //@top-level false 

        /*!
         * @brief Header information used in all generated reply topics.
         */
        struct ReplyHeader
        {
            //! @brief Identification of the client that sends the associated request to this reply.
            dds::SampleIdentity relatedRequestId;
            RemoteExceptionCode_t remoteEx;
        }; //@top-level false 
    };
};
