/*************************************************************************
 * Copyright (c) 2013 eProsima. All rights reserved.
 *
 * This copy of FASTRPC is licensed to you under the terms described in the
 * FASTRPC_LICENSE file included in this distribution.
 *
 *************************************************************************/

typedef octet UnknownOperation;
typedef octet UnknownException;

enum SystemExceptionCode
{
    OK,
    UNIMPLEMENTED,
    BAD_PARAMETER,
    PRECONDITION_NOT_MET,
    OUT_OF_RESOURCES,
    NOT_ENABLED,
    ALREADY_DELETED,
    ILLEGAL_OPERATION,
    TIMEOUT,
    INITIALIZE_ERROR,
    CLIENT_INTERNAL_ERROR,
    SERVER_INTERNAL_ERROR,
    SERVER_NOT_FOUND,
    UNKNOWN
};

struct GUID_t
{
    octet value[16];
}; //@top-level false 

/*!
 * @brief This structure is used to identify clients.
 */
struct SampleIdentity_t
{
    GUID_t guid;
    long long sequence_number;
};

/*!
 * @brief Header information used in all generated request topics.
 */
struct RequestHeader
{
    //! @brief Identification of the client that sends the request.
    SampleIdentity_t request_id;
    //! @brief The service's name of the server that has to take this request.
    string<255> remote_service_name;
    string<255> instance_name;
}; //@top-level false 

/*!
 * @brief Header information used in all generated reply topics.
 */
struct ReplyHeader
{
    //! @brief Identification of the client that sends the associated request to this reply.
    SampleIdentity_t request_id;
}; //@top-level false 
