/*************************************************************************
 * Copyright (c) 2012 eProsima. All rights reserved.
 *
 * This copy of RPCDDS is licensed to you under the terms described in the
 * RPCDDS_LICENSE file included in this distribution.
 *
 *************************************************************************
 * 
 * @file SimpleDelayServerImpl.cxx
 * This source file contains the definition of the skeleton for interface SimpleDelay. This definitions have to be implemented.
 *
 * This file was generated by the tool rpcddsgen.
 */
 
#include "SimpleDelayServerImpl.h"

 
DDS_Long SimpleDelayServerImpl::suma(/*in*/ DDS_Long value1, /*in*/ DDS_Long value2) 
{
    return value1 + value2;
} 
 
Estructura SimpleDelayServerImpl::duplicate(/*in*/ const Estructura& es) 
{
    Estructura duplicate_ret;

    duplicate_ret.short1 = es.short1;
    duplicate_ret.short2 = es.short2;
    duplicate_ret.long1 = es.long1;
    duplicate_ret.long2 = es.long2;
    duplicate_ret.llong1 = es.llong1;
    duplicate_ret.llong2 = es.llong2;
    duplicate_ret.double1 = es.double1;
    duplicate_ret.double2 = es.double2;
    duplicate_ret.string1 = strdup(es.string1);
    duplicate_ret.string2 = strdup(es.string2);
   
    return duplicate_ret;
} 
