/*************************************************************************
 * Copyright (c) 2012 eProsima. All rights reserved.
 *
 * This copy of RPCDDS is licensed to you under the terms described in the
 * RPCDDS_LICENSE file included in this distribution.
 *
 *************************************************************************
 * 
 * @file SimpleDelayRequestReplyUtils.h
 * This header file contains the declaration of helpful functions for the DDS messages for interface SimpleDelay.
 *
 * This file was generated by the tool rpcddsgen.
 */

#ifndef _SimpleDelay_REQUEST_REPLY_UTILS_H_
#define _SimpleDelay_REQUEST_REPLY_UTILS_H_

#include "utils/Messages.h"
#include "SimpleDelayRequestReplySupport.h"

#include "ndds_namespace_cpp.h"


class SimpleDelay_sumaRequestUtils
{
    public:

        /**
         * \brief This function registers the type of the structure SimpleDelay_sumaRequest in the DDS domain participant.
         *
         * \param participant Pointer to the DDS domain participant. Cannot be NULL.
         * \return The type name of the structure SimpleDelay_sumaRequest.
         */
        static const char* registerType(DDS::DomainParticipant *participant);
        
        /**
         * \brief This function sets the parameters into the members of the structure SimpleDelay_sumaRequest.
         *
         * \param instance Pointer to the structure SimpleDelay_sumaRequest that will be filled. Cannot be NULL.
         */
        static void setTypeData(SimpleDelay_sumaRequest& instance, /*in*/ DDS_Long value1, /*in*/ DDS_Long value2);
        
        /**
         * \brief This function extracts the parameters from the members of the structure SimpleDelay_sumaRequest.
         *
         * \param data Pointer to the structure SimpleDelay_sumaRequest that contains the parameters' data. Cannot be NULL.
         */
        static void extractTypeData(SimpleDelay_sumaRequest& data, /*in*/ DDS_Long& value1, /*in*/ DDS_Long& value2);
};


class SimpleDelay_sumaReplyUtils
{
    public:

        /**
         * \brief This function registers the type of the structure SimpleDelay_sumaReply in the DDS domain participant.
         *
         * \param participant Pointer to the DDS domain participant. Cannot be NULL.
         * \return The type name of the structure SimpleDelay_sumaReply.
         */
        static const char* registerType(DDS::DomainParticipant *participant);
        
        /**
         * \brief This function sets the parameters into the members of the structure SimpleDelay_sumaReply.
         *
         * \param instance Pointer to the structure SimpleDelay_sumaReply that will be filled. Cannot be NULL.
         */
        static void setTypeData(SimpleDelay_sumaReply& instance, /*out*/ DDS_Long suma_ret);
        
        /**
         * \brief This function extracts the parameters from the members of the structure SimpleDelay_sumaReply.
         *
         * \param data Pointer to the structure SimpleDelay_sumaReply that contains the parameters' data. Cannot be NULL.
* \param retcode Internal message returned from the server.
         */
        static void extractTypeData(SimpleDelay_sumaReply& data, eProsima::RPCDDS::ReturnMessage& retcode, /*out*/ DDS_Long& suma_ret);
};


class SimpleDelay_duplicateRequestUtils
{
    public:

        /**
         * \brief This function registers the type of the structure SimpleDelay_duplicateRequest in the DDS domain participant.
         *
         * \param participant Pointer to the DDS domain participant. Cannot be NULL.
         * \return The type name of the structure SimpleDelay_duplicateRequest.
         */
        static const char* registerType(DDS::DomainParticipant *participant);
        
        /**
         * \brief This function sets the parameters into the members of the structure SimpleDelay_duplicateRequest.
         *
         * \param instance Pointer to the structure SimpleDelay_duplicateRequest that will be filled. Cannot be NULL.
         */
        static void setTypeData(SimpleDelay_duplicateRequest& instance, /*in*/ const Estructura& es);
        
        /**
         * \brief This function extracts the parameters from the members of the structure SimpleDelay_duplicateRequest.
         *
         * \param data Pointer to the structure SimpleDelay_duplicateRequest that contains the parameters' data. Cannot be NULL.
         */
        static void extractTypeData(SimpleDelay_duplicateRequest& data, /*in*/ Estructura& es);
};


class SimpleDelay_duplicateReplyUtils
{
    public:

        /**
         * \brief This function registers the type of the structure SimpleDelay_duplicateReply in the DDS domain participant.
         *
         * \param participant Pointer to the DDS domain participant. Cannot be NULL.
         * \return The type name of the structure SimpleDelay_duplicateReply.
         */
        static const char* registerType(DDS::DomainParticipant *participant);
        
        /**
         * \brief This function sets the parameters into the members of the structure SimpleDelay_duplicateReply.
         *
         * \param instance Pointer to the structure SimpleDelay_duplicateReply that will be filled. Cannot be NULL.
         */
        static void setTypeData(SimpleDelay_duplicateReply& instance, /*out*/ const Estructura& duplicate_ret);
        
        /**
         * \brief This function extracts the parameters from the members of the structure SimpleDelay_duplicateReply.
         *
         * \param data Pointer to the structure SimpleDelay_duplicateReply that contains the parameters' data. Cannot be NULL.
* \param retcode Internal message returned from the server.
         */
        static void extractTypeData(SimpleDelay_duplicateReply& data, eProsima::RPCDDS::ReturnMessage& retcode, /*out*/ Estructura& duplicate_ret);
};

 
#endif // _SimpleDelay_REQUEST_REPLY_UTILS_H_
