/*************************************************************************
 * Copyright (c) 2012 eProsima. All rights reserved.
 *
 * This copy of RPCDDS is licensed to you under the terms described in the
 * RPCDDS_LICENSE file included in this distribution.
 *
 *************************************************************************
 * 
 * @file SimpleDelayClientRPCSupport.h
 * This header file contains the declaration of the proxy's RPC endpoints for interface SimpleDelay.
 *
 * This file was generated by the tool rpcddsgen.
 */

#ifndef _SimpleDelay_CLIENT_RPC_SUPPORT_H_
#define _SimpleDelay_CLIENT_RPC_SUPPORT_H_

#include "utils/GenericClientRPC.h"
#include "SimpleDelayRequestReplySupport.h"


GENERIC_CLIENT_RPC(SimpleDelay_sumaClientRPC, SimpleDelay_sumaRequestDataWriter, SimpleDelay_sumaReplyDataReader);


GENERIC_CLIENT_RPC(SimpleDelay_duplicateClientRPC, SimpleDelay_duplicateRequestDataWriter, SimpleDelay_duplicateReplyDataReader);


#endif  // _SimpleDelay_CLIENT_RPC_SUPPORT_H_