/*************************************************************************
 * Copyright (c) 2012 eProsima. All rights reserved.
 *
 * This copy of RPCDDS is licensed to you under the terms described in the
 * RPCDDS_LICENSE file included in this distribution.
 *
 *************************************************************************
 * 
 * @file SimpleDelayServerRPCSupport.h
 * This header file contains the declaration of the server's RPC endpoints for interface SimpleDelay.
 *
 * This file was generated by the tool rpcddsgen.
 */

#ifndef _SimpleDelay_SERVER_RPC_SUPPORT_H_
#define _SimpleDelay_SERVER_RPC_SUPPORT_H_

#include "utils/GenericServerRPC.h"
#include "SimpleDelayRequestReplySupport.h"



GENERIC_SERVER_RPC(SimpleDelay_sumaServerRPC, SimpleDelay_sumaReplyDataWriter, SimpleDelay_sumaRequestDataReader);


GENERIC_SERVER_RPC(SimpleDelay_duplicateServerRPC, SimpleDelay_duplicateReplyDataWriter, SimpleDelay_duplicateRequestDataReader);


#endif  // _SimpleDelay_SERVER_RPC_SUPPORT_H_