struct Estructura
{
    short short1;
    short short2;
    long long1;
    long long2;
    long long llong1;
    long long llong2;
    double double1;
    double double2;
    string string1;
    string string2;
};

interface SimpleDelay
{
    long suma(in long value1, in long value2);
    Estructura duplicate(in Estructura es);
};

