#ifndef _RateGen_PROXY_H_
#define _RateGen_PROXY_H_

/** 
 * Generated by DDSCS: Do not edit.  Version 1.0 *
 */

#include "client/DDSCSClient.h"
#include "RateGenRequestReplyUtils.h"
#include "RateGenClientRemoteServiceSupport.h"

class RateGenProxy : public DDSCSClient
{
    public:

        /// \brief The default constructor.
        RateGenProxy(int domainId = 0, unsigned int timeout = 3000);

        /// \brief The default destructor.
        virtual ~RateGenProxy();

        unsigned int getTimeout();
        void setTimeout(unsigned int millis);
        
         
        DDSCSMessages
         suma(DDS_Long id1, DDS_Long id2 ,DDS_Long &suma_ret);
        
    private:
        ClientRemoteService *suma_Service; 
        
        unsigned int m_timeout;
};

#endif // _RateGen_PROXY_H_