/* Generated by opendds_idl.exe version 3.3 (ACE version 5.6a_p13) running on input file idl\Calculator.idl*/
#include "CalculatorTypeSupportImpl.h"



/* Begin INTERFACE: Calculator */


/* End INTERFACE: Calculator */
