// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler v1.6a_p13 ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be\be_codegen.cpp:381


#include "CalculatorRequestReplyC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/String_TypeCode_Static.h"
#include "tao/AnyTypeCode/Struct_TypeCode_Static.h"
#include "tao/AnyTypeCode/TypeCode_Struct_Field.h"
#include "tao/CDR.h"

#if !defined (__ACE_INLINE__)
#include "CalculatorRequestReplyC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be\be_visitor_arg_traits.cpp:73

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_typecode/struct_typecode.cpp:84

static TAO::TypeCode::Struct_Field<
  char const *,
  ::CORBA::TypeCode_ptr const *> const 
    _tao_fields_Calculator_additionRequest[] =
      {
        { "header", &_tc_RequestHeader },
        { "x", &CORBA::_tc_long },
        { "y", &CORBA::_tc_long }
      };
  
static TAO::TypeCode::Struct<
  char const *,
  ::CORBA::TypeCode_ptr const *,
  TAO::TypeCode::Struct_Field<
    char const *,
    ::CORBA::TypeCode_ptr const *> const *,
  TAO::Null_RefCount_Policy>
_tao_tc_Calculator_additionRequest (
  ::CORBA::tk_struct,
  "IDL:Calculator_additionRequest:1.0",
  "Calculator_additionRequest",
  _tao_fields_Calculator_additionRequest,
  3);

::CORBA::TypeCode_ptr const _tc_Calculator_additionRequest =
  &_tao_tc_Calculator_additionRequest;

// TAO_IDL - Generated from 
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_structure/structure_cs.cpp:65



// TAO_IDL - Generated from
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_typecode/struct_typecode.cpp:84

static TAO::TypeCode::Struct_Field<
  char const *,
  ::CORBA::TypeCode_ptr const *> const 
    _tao_fields_Calculator_additionReply[] =
      {
        { "header", &_tc_ReplyHeader },
        { "addition_ret", &CORBA::_tc_long }
      };
  
static TAO::TypeCode::Struct<
  char const *,
  ::CORBA::TypeCode_ptr const *,
  TAO::TypeCode::Struct_Field<
    char const *,
    ::CORBA::TypeCode_ptr const *> const *,
  TAO::Null_RefCount_Policy>
_tao_tc_Calculator_additionReply (
  ::CORBA::tk_struct,
  "IDL:Calculator_additionReply:1.0",
  "Calculator_additionReply",
  _tao_fields_Calculator_additionReply,
  2);

::CORBA::TypeCode_ptr const _tc_Calculator_additionReply =
  &_tao_tc_Calculator_additionReply;

// TAO_IDL - Generated from 
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_structure/structure_cs.cpp:65



// TAO_IDL - Generated from
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_typecode/struct_typecode.cpp:84

static TAO::TypeCode::Struct_Field<
  char const *,
  ::CORBA::TypeCode_ptr const *> const 
    _tao_fields_Calculator_substractionRequest[] =
      {
        { "header", &_tc_RequestHeader },
        { "x", &CORBA::_tc_long },
        { "y", &CORBA::_tc_long }
      };
  
static TAO::TypeCode::Struct<
  char const *,
  ::CORBA::TypeCode_ptr const *,
  TAO::TypeCode::Struct_Field<
    char const *,
    ::CORBA::TypeCode_ptr const *> const *,
  TAO::Null_RefCount_Policy>
_tao_tc_Calculator_substractionRequest (
  ::CORBA::tk_struct,
  "IDL:Calculator_substractionRequest:1.0",
  "Calculator_substractionRequest",
  _tao_fields_Calculator_substractionRequest,
  3);

::CORBA::TypeCode_ptr const _tc_Calculator_substractionRequest =
  &_tao_tc_Calculator_substractionRequest;

// TAO_IDL - Generated from 
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_structure/structure_cs.cpp:65



// TAO_IDL - Generated from
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_typecode/struct_typecode.cpp:84

static TAO::TypeCode::Struct_Field<
  char const *,
  ::CORBA::TypeCode_ptr const *> const 
    _tao_fields_Calculator_substractionReply[] =
      {
        { "header", &_tc_ReplyHeader },
        { "substraction_ret", &CORBA::_tc_long }
      };
  
static TAO::TypeCode::Struct<
  char const *,
  ::CORBA::TypeCode_ptr const *,
  TAO::TypeCode::Struct_Field<
    char const *,
    ::CORBA::TypeCode_ptr const *> const *,
  TAO::Null_RefCount_Policy>
_tao_tc_Calculator_substractionReply (
  ::CORBA::tk_struct,
  "IDL:Calculator_substractionReply:1.0",
  "Calculator_substractionReply",
  _tao_fields_Calculator_substractionReply,
  2);

::CORBA::TypeCode_ptr const _tc_Calculator_substractionReply =
  &_tao_tc_Calculator_substractionReply;

// TAO_IDL - Generated from 
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_structure/structure_cs.cpp:65



// TAO_IDL - Generated from
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_typecode/struct_typecode.cpp:84

static TAO::TypeCode::Struct_Field<
  char const *,
  ::CORBA::TypeCode_ptr const *> const 
    _tao_fields_Calculator_multiplicationRequest[] =
      {
        { "header", &_tc_RequestHeader },
        { "x", &CORBA::_tc_long },
        { "y", &CORBA::_tc_long }
      };
  
static TAO::TypeCode::Struct<
  char const *,
  ::CORBA::TypeCode_ptr const *,
  TAO::TypeCode::Struct_Field<
    char const *,
    ::CORBA::TypeCode_ptr const *> const *,
  TAO::Null_RefCount_Policy>
_tao_tc_Calculator_multiplicationRequest (
  ::CORBA::tk_struct,
  "IDL:Calculator_multiplicationRequest:1.0",
  "Calculator_multiplicationRequest",
  _tao_fields_Calculator_multiplicationRequest,
  3);

::CORBA::TypeCode_ptr const _tc_Calculator_multiplicationRequest =
  &_tao_tc_Calculator_multiplicationRequest;

// TAO_IDL - Generated from 
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_structure/structure_cs.cpp:65



// TAO_IDL - Generated from
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_typecode/struct_typecode.cpp:84

static TAO::TypeCode::Struct_Field<
  char const *,
  ::CORBA::TypeCode_ptr const *> const 
    _tao_fields_Calculator_multiplicationReply[] =
      {
        { "header", &_tc_ReplyHeader },
        { "multiplication_ret", &CORBA::_tc_long }
      };
  
static TAO::TypeCode::Struct<
  char const *,
  ::CORBA::TypeCode_ptr const *,
  TAO::TypeCode::Struct_Field<
    char const *,
    ::CORBA::TypeCode_ptr const *> const *,
  TAO::Null_RefCount_Policy>
_tao_tc_Calculator_multiplicationReply (
  ::CORBA::tk_struct,
  "IDL:Calculator_multiplicationReply:1.0",
  "Calculator_multiplicationReply",
  _tao_fields_Calculator_multiplicationReply,
  2);

::CORBA::TypeCode_ptr const _tc_Calculator_multiplicationReply =
  &_tao_tc_Calculator_multiplicationReply;

// TAO_IDL - Generated from 
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_structure/structure_cs.cpp:65



// TAO_IDL - Generated from
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_typecode/struct_typecode.cpp:84

static TAO::TypeCode::Struct_Field<
  char const *,
  ::CORBA::TypeCode_ptr const *> const 
    _tao_fields_Calculator_divisionRequest[] =
      {
        { "header", &_tc_RequestHeader },
        { "x", &CORBA::_tc_long },
        { "y", &CORBA::_tc_long }
      };
  
static TAO::TypeCode::Struct<
  char const *,
  ::CORBA::TypeCode_ptr const *,
  TAO::TypeCode::Struct_Field<
    char const *,
    ::CORBA::TypeCode_ptr const *> const *,
  TAO::Null_RefCount_Policy>
_tao_tc_Calculator_divisionRequest (
  ::CORBA::tk_struct,
  "IDL:Calculator_divisionRequest:1.0",
  "Calculator_divisionRequest",
  _tao_fields_Calculator_divisionRequest,
  3);

::CORBA::TypeCode_ptr const _tc_Calculator_divisionRequest =
  &_tao_tc_Calculator_divisionRequest;

// TAO_IDL - Generated from 
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_structure/structure_cs.cpp:65



// TAO_IDL - Generated from
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_typecode/struct_typecode.cpp:84

static TAO::TypeCode::Struct_Field<
  char const *,
  ::CORBA::TypeCode_ptr const *> const 
    _tao_fields_Calculator_divisionReply[] =
      {
        { "header", &_tc_ReplyHeader },
        { "division_ret", &CORBA::_tc_long }
      };
  
static TAO::TypeCode::Struct<
  char const *,
  ::CORBA::TypeCode_ptr const *,
  TAO::TypeCode::Struct_Field<
    char const *,
    ::CORBA::TypeCode_ptr const *> const *,
  TAO::Null_RefCount_Policy>
_tao_tc_Calculator_divisionReply (
  ::CORBA::tk_struct,
  "IDL:Calculator_divisionReply:1.0",
  "Calculator_divisionReply",
  _tao_fields_Calculator_divisionReply,
  2);

::CORBA::TypeCode_ptr const _tc_Calculator_divisionReply =
  &_tao_tc_Calculator_divisionReply;

// TAO_IDL - Generated from 
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_structure/structure_cs.cpp:65



// TAO_IDL - Generated from
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_structure/cdr_op_cs.cpp:61


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Calculator_additionRequest &_tao_aggregate
  )
{
  return
    (strm << _tao_aggregate.header) &&
    (strm << _tao_aggregate.x) &&
    (strm << _tao_aggregate.y);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Calculator_additionRequest &_tao_aggregate
  )
{
  return
    (strm >> _tao_aggregate.header) &&
    (strm >> _tao_aggregate.x) &&
    (strm >> _tao_aggregate.y);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_structure/cdr_op_cs.cpp:61


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Calculator_additionReply &_tao_aggregate
  )
{
  return
    (strm << _tao_aggregate.header) &&
    (strm << _tao_aggregate.addition_ret);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Calculator_additionReply &_tao_aggregate
  )
{
  return
    (strm >> _tao_aggregate.header) &&
    (strm >> _tao_aggregate.addition_ret);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_structure/cdr_op_cs.cpp:61


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Calculator_substractionRequest &_tao_aggregate
  )
{
  return
    (strm << _tao_aggregate.header) &&
    (strm << _tao_aggregate.x) &&
    (strm << _tao_aggregate.y);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Calculator_substractionRequest &_tao_aggregate
  )
{
  return
    (strm >> _tao_aggregate.header) &&
    (strm >> _tao_aggregate.x) &&
    (strm >> _tao_aggregate.y);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_structure/cdr_op_cs.cpp:61


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Calculator_substractionReply &_tao_aggregate
  )
{
  return
    (strm << _tao_aggregate.header) &&
    (strm << _tao_aggregate.substraction_ret);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Calculator_substractionReply &_tao_aggregate
  )
{
  return
    (strm >> _tao_aggregate.header) &&
    (strm >> _tao_aggregate.substraction_ret);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_structure/cdr_op_cs.cpp:61


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Calculator_multiplicationRequest &_tao_aggregate
  )
{
  return
    (strm << _tao_aggregate.header) &&
    (strm << _tao_aggregate.x) &&
    (strm << _tao_aggregate.y);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Calculator_multiplicationRequest &_tao_aggregate
  )
{
  return
    (strm >> _tao_aggregate.header) &&
    (strm >> _tao_aggregate.x) &&
    (strm >> _tao_aggregate.y);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_structure/cdr_op_cs.cpp:61


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Calculator_multiplicationReply &_tao_aggregate
  )
{
  return
    (strm << _tao_aggregate.header) &&
    (strm << _tao_aggregate.multiplication_ret);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Calculator_multiplicationReply &_tao_aggregate
  )
{
  return
    (strm >> _tao_aggregate.header) &&
    (strm >> _tao_aggregate.multiplication_ret);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_structure/cdr_op_cs.cpp:61


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Calculator_divisionRequest &_tao_aggregate
  )
{
  return
    (strm << _tao_aggregate.header) &&
    (strm << _tao_aggregate.x) &&
    (strm << _tao_aggregate.y);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Calculator_divisionRequest &_tao_aggregate
  )
{
  return
    (strm >> _tao_aggregate.header) &&
    (strm >> _tao_aggregate.x) &&
    (strm >> _tao_aggregate.y);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\richi\workspace\desarrollo\dds\opendds\instalaciones\opendds3.3\ace_wrappers_x64\tao\tao_idl\be\be_visitor_structure/cdr_op_cs.cpp:61


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Calculator_divisionReply &_tao_aggregate
  )
{
  return
    (strm << _tao_aggregate.header) &&
    (strm << _tao_aggregate.division_ret);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Calculator_divisionReply &_tao_aggregate
  )
{
  return
    (strm >> _tao_aggregate.header) &&
    (strm >> _tao_aggregate.division_ret);
}

TAO_END_VERSIONED_NAMESPACE_DECL



