/* -*- C++ -*- */
/* Generated by opendds_idl.exe version 3.3 (ACE version 5.6a_p13) running on input file idl\Calculator.idl*/
#ifndef OPENDDS_IDL_GENERATED_CALCULATORTYPESUPPORTIMPL_H_VI2PCU
#define OPENDDS_IDL_GENERATED_CALCULATORTYPESUPPORTIMPL_H_VI2PCU
#include "dds/DCPS/Definitions.h"
#include "CalculatorC.h"


/* Begin INTERFACE: Calculator */


/* End INTERFACE: Calculator */
#endif /* OPENDDS_IDL_GENERATED_CALCULATORTYPESUPPORTIMPL_H_VI2PCU */
