@Annotation
local interface RESOURCES_BASE_URI {
	attribute string value;
};

@RESOURCES_BASE_URI("http://example.com/resources/")
module Bank
{
	@Annotation
	local interface PATH {
		attribute string value;
	};

	@Annotation
	local interface METHOD {
		attribute string value;
	};

	@Annotation
	local interface BODY {
		attribute string value;
	};

	@PATH("account/{accountNumber}")
	interface account_accountNumberResource
	{
		struct account_accountNumber
		{
			long accountNumber_;
		};

		struct EmptyGetAccountDetailsResponse
		{
			long status;
		};

		struct XMLGetAccountDetailsResponse
		{
			long status;
			string xmlRepresentation;
		};

		union GetAccountDetailsResponse switch(long)
		{
			case 0:
				EmptyGetAccountDetailsResponse emptyGetAccountDetailsResponse;
			case 1:
				XMLGetAccountDetailsResponse xmlGetAccountDetailsResponse;
		};

		union GetAccountDetailsRequest switch(long)
		{
			case 1:
				string xmlRepresentation;
		};

		@METHOD("POST")
		@BODY("GetAccountDetailsRequest")
		GetAccountDetailsResponse getAccountDetails(in account_accountNumber account_accountNumber, in string user, in GetAccountDetailsRequest GetAccountDetailsRequest);

	};

};

