/*************************************************************************
 * Copyright (c) 2012 eProsima. All rights reserved.
 *
 * This copy of RPCDDS is licensed to you under the terms described in the
 * RPCDDS_LICENSE file included in this distribution.
 *
 *************************************************************************
 * 
 * @file MultithreadTestAsyncSupport.h
 * This header file contains functionality to use asynchronous calls for interface MultithreadTest.
 *
 * This file was generated by the tool rpcddsgen.
 */

#ifndef _MultithreadTest_ASYNC_SUPPORT_H_
#define _MultithreadTest_ASYNC_SUPPORT_H_

#include "client/AsyncTask.h"


/**
 * \brief This class represents a asynchronous task created to wait the reply of the procedure test from the server in an asynchronous call.
 */
class MultithreadTest_testTask : public eProsima::RPCDDS::AsyncTask
{
    public:

        /**
         * \brief The default constructor.
         *
         * \param obj Object that implements the callbacks that RPCDDS will call when
         *            the reply will be received or and exception will be launched.
         * \param client Pointer to the server's proxy. Cannot be NULL.
         */
        MultithreadTest_testTask(MultithreadTest_testCallbackHandler &obj,
           eProsima::RPCDDS::Client *client);

        /// \brief The default destructor.
        virtual ~MultithreadTest_testTask();
        
        virtual void execute();
        
        virtual void on_exception(const eProsima::RPCDDS::SystemException &ex);
        
        /**
         * \brief This function returns the object used by the task.
         *
         * \return The object that implements the callbacks.
         */
        MultithreadTest_testCallbackHandler& getObject();
        
        void* getReplyInstance();
        
        private:
        
           MultithreadTest_testCallbackHandler &m_obj;
           
           MultithreadTest_testReply m_reply;
};

#endif // _MultithreadTest_ASYNC_SUPPORT_H_