#ifndef _UnionTestSKELETON_H_
#define _UnionTestSKELETON_H_

/** 
 * Generated by DDSCS: Do not edit.  Version 1.0 *
 */

#include "server/DDSCSServer.h"
#include "UnionTestServerImpl.h"
#include "UnionTestRequestReplyUtils.h"

class UnionTestServer : public DDSCSServer
{
    private: 
      UnionTestImpl *_impl;
    public:

        /// \brief The default constructor.
        UnionTestServer(int domainId = 0, const char *qosLibrary = NULL,
            const char *qosProfile = NULL, unsigned int threadCount = DDSCS_MIN_THREADS_DEFAULT);

        /// \brief The default destructor.
        virtual ~UnionTestServer();

        static void getEmpleado(DDSCSServer *server, void *requestData, ServerRemoteService *service);
};

#endif // _UnionTestSKELETON_H_
