#ifndef _UnionTest_SERVER_REMOTE_SERVICE_SUPPORT_H_
#define _UnionTest_SERVER_REMOTE_SERVICE_SUPPORT_H_

/** 
 * Generated by DDSCS: Do not edit.  Version 1.0 *
 */

#include "utils/GenericServerRemoteService.h"
#include "UnionTestRequestReplySupport.h"


GENERIC_SERVER_REMOTE_SERVICE(getEmpleadoServerRemoteService, getEmpleadoReplyDataWriter, getEmpleadoRequestDataReader);


#endif  // _UnionTest_SERVER_REMOTE_SERVICE_SUPPORT_H_