/** 
 * Generated by DDSCS: Do not edit.  Version 1.0 *
 */

#include "server/DDSCSServer.h"
#include "TypedefTestServerRemoteServiceSupport.h"


/* Defines */
#define TName                   getLargoServerRemoteService
#define TDataReplyTypeSupport   getLargoReplyTypeSupport
#define TDataRequestTypeSupport getLargoRequestTypeSupport
#define TData                   getLargo
#define TDataReader             getLargoRequestDataReader
#define TDataWriter             getLargoReplyDataWriter


#include "utils/GenericServerRemoteService.gen"


#undef TName
#undef TDataReplyTypeSupport
#undef TDataRequestTypeSupport
#undef TData
#undef TDataReader
#undef TDataWriter


/* Defines */
#define TName                   getLarguisimoServerRemoteService
#define TDataReplyTypeSupport   getLarguisimoReplyTypeSupport
#define TDataRequestTypeSupport getLarguisimoRequestTypeSupport
#define TData                   getLarguisimo
#define TDataReader             getLarguisimoRequestDataReader
#define TDataWriter             getLarguisimoReplyDataWriter


#include "utils/GenericServerRemoteService.gen"


#undef TName
#undef TDataReplyTypeSupport
#undef TDataRequestTypeSupport
#undef TData
#undef TDataReader
#undef TDataWriter


/* Defines */
#define TName                   getDatosDefServerRemoteService
#define TDataReplyTypeSupport   getDatosDefReplyTypeSupport
#define TDataRequestTypeSupport getDatosDefRequestTypeSupport
#define TData                   getDatosDef
#define TDataReader             getDatosDefRequestDataReader
#define TDataWriter             getDatosDefReplyDataWriter


#include "utils/GenericServerRemoteService.gen"


#undef TName
#undef TDataReplyTypeSupport
#undef TDataRequestTypeSupport
#undef TData
#undef TDataReader
#undef TDataWriter


/* Defines */
#define TName                   getDatosDefondoServerRemoteService
#define TDataReplyTypeSupport   getDatosDefondoReplyTypeSupport
#define TDataRequestTypeSupport getDatosDefondoRequestTypeSupport
#define TData                   getDatosDefondo
#define TDataReader             getDatosDefondoRequestDataReader
#define TDataWriter             getDatosDefondoReplyDataWriter


#include "utils/GenericServerRemoteService.gen"


#undef TName
#undef TDataReplyTypeSupport
#undef TDataRequestTypeSupport
#undef TData
#undef TDataReader
#undef TDataWriter


/* Defines */
#define TName                   getCadenaServerRemoteService
#define TDataReplyTypeSupport   getCadenaReplyTypeSupport
#define TDataRequestTypeSupport getCadenaRequestTypeSupport
#define TData                   getCadena
#define TDataReader             getCadenaRequestDataReader
#define TDataWriter             getCadenaReplyDataWriter


#include "utils/GenericServerRemoteService.gen"


#undef TName
#undef TDataReplyTypeSupport
#undef TDataRequestTypeSupport
#undef TData
#undef TDataReader
#undef TDataWriter


/* Defines */
#define TName                   getCorreaServerRemoteService
#define TDataReplyTypeSupport   getCorreaReplyTypeSupport
#define TDataRequestTypeSupport getCorreaRequestTypeSupport
#define TData                   getCorrea
#define TDataReader             getCorreaRequestDataReader
#define TDataWriter             getCorreaReplyDataWriter


#include "utils/GenericServerRemoteService.gen"


#undef TName
#undef TDataReplyTypeSupport
#undef TDataRequestTypeSupport
#undef TData
#undef TDataReader
#undef TDataWriter

